config/routes.rb
Rails.application.routes.draw do
	resources :items
	root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy ]
	def index
		@item = Item.all.order("created_at DESC")
	end
	def show
	end
	def new
	@item = Item.new
	end
	def create
	@item = Item.new(item_params)
	if @item.save
	redirect_to root_path
	else
	render 'new'
	end
	end
	def edit
	end
	def update
		if @item.update(item_params)
		redirect_to item_path(@item)
		else
		render 'edit'
		end
	end
	
	def destroy
		@item.destroy
		redirect_to root_path
	end
	
	private 
	def item_params
		params.require(:item).permit(:title, :description)
		
	end
	def find_item
		@item = Item.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
<h1>Title</h1>
<%= f.text_field :title %>
<h1>Description</h1>
<%= f.text_field :description %>
<br>
<%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Checklist Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<% @item.each do |item| %>
<h1><%= link_to item.title, item %></h1>
<p><%= item.description %></p>
<% end %>

app/views/items/new.html.erb
<h1> New Checklist Item </h1>

<%= render 'form' %>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<p><%= @item.description %></p>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_item_path(@item) %>
<%= link_to "Delete", item_path(@item), method: :delete, data: {confirm: "Are yo sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>